domain: wordpress-plugins-world.github.io/wordpress-agile-scrum-project-management       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://wordpress-plugins-world.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /wordpress-agile-scrum-project-management/      # place folder name if the site is served in a subfolder
